# Generated by Django 5.0.2 on 2024-02-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name1', models.CharField(max_length=255)),
                ('school_name2', models.CharField(max_length=255)),
                ('school_address', models.CharField(max_length=255)),
            ],
        ),
    ]
